### ISSUE TITLE
OSX El Capitan cannot download the installer from the captive portal.

### ISSUE THREAD

**Issue by MathJud** [WachterJud/qaul.net#108]
Apple changed the behaviour of it's login browser with captive portals. 
The login browser opens the download link with the default web browser. 
The web browser is then told by the system that no network connection exists.

Ideas and solutions are welcome

**Comment by deavmi** [comment]
Oh. Does it have a problem checking for an Internet connection? And that wouldn't work on an offline mesh net?

**Comment by MathJud** [comment]
Someone told me that it can be configured on a per network basis in OSX and iOS.
If this works, we should show implement an screenshot based explanation for those systems how a user can do that.

**Comment by deavmi** [comment]
Sounds good @MathJud :+1:

**Comment by MathJud** [comment]
OSX checks for the URL "http://captive.apple.com/hotspot-detect.html" and needs to be returned the following HTML:

```
<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>
```
