### ISSUE TITLE
CLI-client automation

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net#123]
> CLI-client does not configure Wifi, networking or routing. The network interfaces have to be configured manually before starting the CLI client. The routing protocol olsrd has to be started manually to.

Will the CLI version automatically configure everything like the GTK version does oneday?

**Comment by MathJud** [comment]
The new qaul linux daemon (qauld) takes the place of the cli-client.
The daemon can configure the network (wifi, ip address, olsrd, firewall, etc.) like qaul-gtk
In the future the current cli-client will be removed and hopefully replaced by a real cli-client.

**Comment by deavmi** [comment]
Ok :)

**Comment by deavmi** [comment]
Awesome :+1:
