### ISSUE TITLE
Publish build system?

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net#138]
Could you publish the build system you use to build new binaries on new commits?

**Comment by MathJud** [comment]
qaul.net uses the build system of [gitlab-ci](https://about.gitlab.com/gitlab-ci/) for it's continous integration.
The configuration to create those builds is in the repository file [.gitlab-ci.yml](https://github.com/WachterJud/qaul.net/blob/qaul-ng/.gitlab-ci.yml) . 
Everyone can set up ones own gitlab server and start building his/her own binaries.

**Comment by deavmi** [comment]
Awesome. Thanks.
