### ISSUE TITLE
Headless dedicated node builds

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net#140]
I think it would be really awesome to see headless builds with no voip, chat or file sharing but with the easy to setup Qaul network system. 

As then people an easily install it on a Raspberry Pi running Raspbian in console mode and create a real dedicated node.

These builds could also disable the Qaul web interface but keep the show network interface (i don't know, maybe - maybe not).

If you see where I am going.

**Comment by MathJud** [comment]
Yep!!!
Our plans are to create Raspber-pi and openWRT/LEDE images to easily create seeding nodes as well as infrastructure nodes.

**Comment by deavmi** [comment]
Awesome.

**Comment by deavmi** [comment]
Seeding nodes?

**Comment by deavmi** [comment]
Also. Take a look at the Babel routing protocol. There is a blog post on how to set it up. http://www.ericerfanian.com/mobile-mesh-networks-with-the-raspberry-pi-part-3/

Maybe we could attempt integrating it into Qaul. Need to see if it will build on Windows and MacOSX tho.

**Comment by deavmi** [comment]
Also, will the CLI builds be able to start olsr router soon? If I am correct they don't do any network configuration yet?

**Comment by MathJud** [comment]
qauld can be run headless on  raspbian.
The configuration can be done directly in the data base following the documentation: 
https://github.com/WachterJud/qaul.net/blob/qaul-ng/doc/CLI-Client_Configuration.md

It should become easier once issue #65  is solved.
