### ISSUE TITLE
No CSS?

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net#149]
Ran the latest version of `qaul-gtk` from the terminal and when viewing the pages there seemed to be a lack of styling applied to them?

![screenshot from 2016-07-12 19 04 01](https://cloud.githubusercontent.com/assets/5207740/16776001/9bc30bca-4863-11e6-874f-ec6099abd016.png)

**Comment by deavmi** [comment]
This page didn't seem to be working all that well either.

![screenshot from 2016-07-12 19 06 44](https://cloud.githubusercontent.com/assets/5207740/16776065/dd224536-4863-11e6-8004-be62b26f8172.png)

It didn't show any nodes (it should of shown one - myself)

**Comment by MathJud** [comment]
As your screenshot quotes, you might have to enable java-script in your browser to see the nodes (and most probably also the index page).

**Comment by deavmi** [comment]
I have enabled it though. Let me check again.

**Comment by deavmi** [comment]
I am very sure my javascript is enabled.

**Comment by deavmi** [comment]
Yeah, it is. So sure.

**Comment by MathJud** [comment]
I can't verify this issue. Does it still exist?
The CSS file (qaul_web.css) is in all the install packages. 
It is located under: /usr/local/lib/qaul/www/qaul_web.css

**Comment by deavmi** [comment]
I will test this again.
