### ISSUE TITLE
Switch to batman-adv

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net#85]
Batman-adv is way better than olsrd. And has reactive routing which is way better in performance and reliability.

**Comment by MathJud** [comment]
Unfortunately Batman-adv is only running on Linux. As qaul.net supports many OSs we can't use this protocol.

**Comment by deavmi** [comment]
Are there no ports?

**Comment by MathJud** [comment]
Unfortunately not.

**Comment by deavmi** [comment]
What about the newer bmx6?

**Comment by deavmi** [comment]
Have you looked into the following?:

* Babel: https://www.irif.univ-paris-diderot.fr/~jch/software/babel/
* bmx6: http://bmx6.net/projects/bmx6

Or cjdns? (Which I think could work on all Demario platforms (android possibly one day - somebody was working on an android version I think))

**Comment by MathJud** [comment]
I know these protocols.
It would be cool to be able to use different protocols. For that, one would need an own mesh-enabled message floader. At the moment qaul.net uses the flooding system of olsrd.
 
cjdns is an Internet overlay network, it is not suitable for a quickly changeable mobile wifi mesh routing.

**Comment by deavmi** [comment]
cjdns can be used in a non-overlay way it can do MAC-routing apparently.

**Comment by deavmi** [comment]
Hopefully a build of batman-adv for Mac will happen soon. Is it suitable for mesh networks with nodes moving around and re-configuring a lot?

**Comment by deavmi** [comment]
And Windows...
